[project]
name = "marimol"
version = "0.1.0"
description = "Molecular visualizer for marimo notebooks"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Pedro Juan Royo", email = "pedro.juan.royo@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "anywidget>=0.11.0",
    "marimo>=0.23.16",
    "numpy>=2",
    "traitlets>=5.16.1",
]

[project.optional-dependencies]
external = [
    "ase",
    "pymatgen",
]
all = [
    "marimol[external]",
]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "prek>=0.4.12",
    "ruff>=0.16.2",
]

[tool.ruff]
line-length = 120
target-version = "py311"
extend-exclude = ["docs"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP", # pyupgrade
]
ignore = [
    "E501", # line too long, let formatter handle it
]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
